project:
  type: website

website:
  google-analytics: 
    tracking-id: "G-41DNWB0BJ3"
    storage: none
    anonymize-ip: true
  title: "Liam's Learning"
  navbar:
    left:
      - 100-days-of-pytorch.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/liamgroen


format:
  html:
    respect-user-color-scheme: true
    theme:
      light: 
      - cosmo
      - brand
      dark:
      - darkly
      - brand
    css: styles.css

execute:
  freeze: auto

