project:
  type: website

website:
  title: "Learning Journey: MacSuperior's Blog"
  navbar:
    left:
      - 100-days-of-pytorch.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/MacSuperior

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css


execute:
  freeze: auto

