project:
  type: website

website:
  title: "Liam's Learning"
  description: "Posts about machine learning, deep learning, math and coding."
  site-url: "https://liamgroen.nl"
  image: "/site-image.jpg"
  open-graph: true
  google-analytics: 
    tracking-id: "G-41DNWB0BJ3"
    storage: none
    anonymize-ip: true
  navbar:
    left:
      - 100-days-of-pytorch.qmd
      - posts.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/liamgroen
  announcement: 
    icon: info-circle
    dismissable: true
    type: info
    position: below-navbar
    content: Daily '100 day' updates will resume at the end of June, when I will be done with my exams.


format:
  html:
    respect-user-color-scheme: true
    theme:
      light: 
      - cosmo
      - brand
      dark:
      - darkly
      - brand
    css: styles.css

execute:
  freeze: auto

